categories:
  moda:
    feeds:
      - https://www.vogue.com/fashion/rss
      - https://www.highsnobiety.com/feed/
    keywords:
      include: ["tendencia", "runway", "estilo", "colección"]
      exclude: ["descuento", "oferta"]
  gastronomia:
    feeds:
      - https://www.finedininglovers.com/rss
      - https://bonviveur.elmundo.es/rss
    keywords:
      include: ["chef", "experiencia gourmet", "estrella Michelin", "alta cocina"]
      exclude: ["receta fácil", "recetas básicas"]
  arte:
    feeds:
      - https://www.theartnewspaper.com/rss
      - https://elcultural.com/feed
    keywords:
      include: ["exposición", "obra", "cultura", "artista"]
  lifestyle:
    feeds:
      - https://www.cntraveler.com/feed
      - https://www.hospitalitynet.org/topics/feed
    keywords:
      include: ["experiencia", "lujo", "exclusividad", "wellness"]
  local:
    feeds:
      - https://www.laopiniondemalaga.es/rss/section/1622
      - https://www.diariosur.es/rss/2.0/local
    keywords:
      include: ["Málaga", "Costa del Sol", "Andalucía", "Marbella"]

global_keywords:
  include: ["lujo", "luxury", "exclusivo", "cinco estrellas", "diseño", "gourmet", "boutique", "alta gama", "sofisticación"]