feeds:
moda:
  - https://rss.app/feeds/_xkaEr3XQrgKrUJAK.xml
gastronomia:
  - https://rss.app/feeds/_Pt3I0RDdPJf8gbnI.xml
arte_cultura:
  - https://rss.app/feeds/_a2wvyoGTdkAFrBBn.xml
lifestyle:
  - https://rss.app/feeds/_FWuJEHOtZPo8Fuwh.xml
malaga:
  - https://rss.app/feeds/_0R6Eg3bnjjj5hZRL.xml
