name: Collect Trends

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"   # cada día a las 06:00 UTC

permissions:
  contents: write   # necesario para poder hacer git push

jobs:
  collect:
    runs-on: ubuntu-latest

    env:
      # 🔑 Claves (rotación por comas: KEY1,KEY2,KEY3). Mantén GEMINI_API_KEY como fallback si quieres.
      GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
      GEMINI_API_KEY:  ${{ secrets.GEMINI_API_KEY }}

      # 🐢 Ritmo MUY prudente (ajústalo sin tocar código)
      GEMINI_SECONDS_PER_CALL: "12"   # 12s por llamada/clave ≈ 5 rpm por proyecto
      # GEMINI_RPM_PER_KEY: "5"       # alternativa a la línea de arriba

      # 📉 Límites conservadores
      PER_CATEGORY_LIMIT: "30"
      MAX_TOTAL_ARTICLES: "120"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run trend collector
        run: python trend_probe.py

      # (Opcional pero MUY útil) Artefactos para descargar los JSON desde la página del run
      - name: Upload JSONs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: aura-trends-json
          path: data/*.json
          if-no-files-found: warn

      # Commit & push solo si hay cambios, con shell robusto
      - name: Commit & push changes if any
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/curated.json data/trends.json || true
          if git diff --cached --quiet; then
            echo "No hay cambios que commitear."
          else
            git commit -m "Update trends $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
