name: Collect Trends

on:
  schedule:
    - cron: '0 6,14 * * *'  # 08:00 y 16:00 hora Madrid (UTC+2)
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run trend collector
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python trend_probe.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/trends.json
          git commit -m "Update trends data" || echo "No changes to commit"
          git push
        continue-on-error: true
