name: Collect Trends

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8,18 * * *"  # Corre todos los días a las 08:00 y 18:00 UTC

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python trend_probe.py
